# Generates Adafruit-GFX font headers from the Space Grotesk variable TTF.
# Glyphs are rendered antialiased and thresholded at 50% (same as the preview).
# Character codes are Latin-1, so C++ strings use \xE4 etc. for umlauts and µ ³ ° ·.
# Only the characters listed per font are included (others get empty glyphs).
import string
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

SG = Path(__file__).parent.parent / "assets" / "fonts" / "SpaceGrotesk.ttf"
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent / "fonts_out"

DIGITS = "0123456789.-"
CAPS = string.ascii_uppercase + string.digits + " .,:-"

# name, size(px), weight, chars, tabular digits
FONTS = [
    ("SG_Caps10", 10, 600, CAPS + "gm/+%\u00b5\u00b3\u00b0", False),       # scale labels and units
    ("SG_Caps13", 13, 600, CAPS + "%", False),                             # date, metric labels
    ("SG_Sub13", 13, 500, "Particles good moderate high VOC\u00b7", False),  # status reason
    ("SG_Head18", 18, 600, CAPS + ":\u00b0%", True),                       # date, time, temp, rh
    ("SG_Value20", 20, 500, DIGITS, True),                                 # bottom values
    ("SG_Value26", 26, 500, DIGITS, True),                                 # PM2.5 / VOC
    ("SG_Boot28", 28, 700, "AIR MONT", False),                            # boot wordmark
    ("SG_Status36", 36, 700, "GoodModeratePr", False),                     # status word
    ("SG_Info12", 12, 500, string.printable[:95], False),                  # readable ASCII addresses and setup text
]


def build(name, size, wght, chars, tnum):
    font = ImageFont.truetype(str(SG), size)
    font.set_variation_by_axes([wght])
    codes = sorted({ord(c) for c in chars} | {0x20})
    first, last = codes[0], codes[-1]
    bitmap = bytearray()
    glyphs = []
    for code in range(first, last + 1):
        ch = chr(code)
        if code not in codes:
            glyphs.append((len(bitmap), 0, 0, 0, 0, 0, ch))
            continue
        feats = ["tnum"] if tnum and ch.isdigit() else None
        adv = round(font.getlength(ch, features=feats))
        x0, y0, x1, y1 = font.getbbox(ch, anchor="ls", features=feats)
        pad = 3
        img = Image.new("L", (x1 - x0 + 2 * pad, y1 - y0 + 2 * pad), 0)
        ImageDraw.Draw(img).text((pad - x0, pad - y0), ch, font=font, anchor="ls", fill=255, features=feats)
        img = img.point(lambda v: 255 if v >= 128 else 0)
        ink = img.getbbox()
        if ch == " " or ink is None:
            glyphs.append((len(bitmap), 0, 0, adv, 0, 0, ch))
            continue
        ix0, iy0, ix1, iy1 = ink
        w, h = ix1 - ix0, iy1 - iy0
        xo, yo = x0 - pad + ix0, y0 - pad + iy0
        px = img.load()
        acc, nbits = 0, 0
        offset = len(bitmap)
        for yy in range(iy0, iy1):
            for xx in range(ix0, ix1):
                acc = (acc << 1) | (1 if px[xx, yy] else 0)
                nbits += 1
                if nbits == 8:
                    bitmap.append(acc); acc, nbits = 0, 0
        if nbits:
            bitmap.append(acc << (8 - nbits))
        glyphs.append((offset, w, h, adv, xo, yo, ch))
    ascent, descent = font.getmetrics()
    y_adv = ascent + descent

    lines = ["#pragma once", "",
             f"// Space Grotesk {wght}, {size}px, Latin-1 subset. Generated by gen_gfx_fonts.py.",
             f"// Space Grotesk is licensed under the SIL Open Font License 1.1.", "",
             f"const uint8_t {name}Bitmaps[] PROGMEM = {{"]
    for i in range(0, len(bitmap), 12):
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 12]) + ",")
    if not bitmap:
        lines.append("  0x00")
    lines += ["};", "", f"const GFXglyph {name}Glyphs[] PROGMEM = {{"]
    for off, w, h, adv, xo, yo, ch in glyphs:
        # never end a // comment with a backslash (it would swallow the next line)
        label = ch if ch.isalnum() and ord(ch) < 0x7F else f"U+{ord(ch):04X}"
        lines.append(f"  {{ {off:5d}, {w:3d}, {h:3d}, {adv:3d}, {xo:4d}, {yo:4d} }},   // 0x{ord(ch):02X} {label}")
    lines += ["};", "",
              f"const GFXfont {name} PROGMEM = {{",
              f"  (uint8_t  *){name}Bitmaps,",
              f"  (GFXglyph *){name}Glyphs,",
              f"  0x{first:02X}, 0x{last:02X}, {y_adv} }};", "",
              f"// Approx. {len(bitmap) + 7 * len(glyphs) + 7} bytes", ""]
    (OUT / f"{name}.h").write_text("\n".join(lines))
    return len(bitmap) + 7 * len(glyphs) + 7


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    total = 0
    for spec in FONTS:
        n = build(*spec)
        total += n
        print(f"{spec[0]:12s} {n:6d} bytes")
    print(f"total        {total:6d} bytes")
